import { timingSafeEqual } from 'node:crypto';
import { mkdir, rm } from 'node:fs/promises';
import type { FastifyInstance, FastifyRequest } from 'fastify';
import fastifyStatic from '@fastify/static';
import { authConfig } from '../auth/auth.config.js';
import { sendAlert } from '../alerts/ntfy.js';
import { loadServer } from '../servers/servers.loader.js';
import { loadReportsConfig } from './reports.config.js';
import { REPORT_SUBDIR, extract, list, newId, prune, remove, writeMeta } from './reports.store.js';
import type { ReportMeta } from './reports.types.js';

type IngestQuery = {
  node?: string;
  repo?: string;
  pr?: string;
  branch?: string;
  sha?: string;
  run?: string;
  title?: string;
  status?: string;
};

/** Bearer token compare that doesn't leak the token's prefix via timing. */
function tokenMatches(header: string | undefined, expected: string): boolean {
  const got = header?.startsWith('Bearer ') ? header.slice(7).trim() : '';
  const a = Buffer.from(got);
  const b = Buffer.from(expected);
  // timingSafeEqual throws on a length mismatch, so gate on it first. Length is
  // not the secret here — the token is fixed-width and generated by us.
  return a.length === b.length && timingSafeEqual(a, b);
}

/** Public viewing URL for a report — what the ntfy push and the UI both link to. */
function viewUrl(id: string, base: string): string {
  return `${base}/api/reports/view/${id}/${REPORT_SUBDIR}/index.html`;
}

function alertFor(meta: ReportMeta, url: string) {
  const where = [
    meta.repo && meta.pr ? `${meta.repo} #${meta.pr}` : meta.repo,
    meta.branch,
    meta.sha?.slice(0, 8),
  ].filter(Boolean).join(' · ');

  return sendAlert({
    title: `E2E failed — ${meta.repo ?? meta.node}`,
    body: [
      `node:   ${meta.node}`,
      where ? `where:  ${where}` : '',
      meta.runUrl ? `run:    ${meta.runUrl}` : '',
      '',
      'Tap to open the Playwright report (videos + traces).',
      url,
    ].filter(Boolean).join('\n'),
    priority: 'high',
    tags: ['rotating_light'],
    click: url,
  });
}

/**
 * Hosting for Playwright HTML reports pushed up by CI.
 *
 *   POST   /api/reports/ingest?node=…   bearer-token, gzipped tarball body
 *   GET    /api/reports?node=…          list metadata (session)
 *   DELETE /api/reports/:id             (session)
 *   GET    /api/reports/view/<id>/…     the report itself (session)
 *
 * The ingest route is the ONE path in the app that isn't behind Discord OAuth
 * (see auth.plugin.ts) — GitHub Actions can't do an interactive login, so a
 * bearer token is the whole gate. It's an exact-path carve-out, the compare is
 * timing-safe, and an unset REPORTS_INGEST_TOKEN closes the route entirely
 * rather than defaulting to something guessable.
 *
 * `node` is validated against config/servers, so every report is anchored to a
 * real node — that's what lets the dashboard's node detail list them.
 */
export async function reportsRoutes(app: FastifyInstance) {
  const cfg = loadReportsConfig();
  await mkdir(cfg.dir, { recursive: true });

  // Hand the raw request stream to the route instead of buffering it — a report
  // with failure videos is tens of MB and must never land in the pod's heap.
  app.addContentTypeParser(
    ['application/gzip', 'application/x-gzip', 'application/octet-stream'],
    (_req, payload, done) => done(null, payload),
  );

  app.post<{ Querystring: IngestQuery }>(
    '/api/reports/ingest',
    { bodyLimit: cfg.maxBytes },
    async (req: FastifyRequest<{ Querystring: IngestQuery }>, reply) => {
      const { token, keep } = loadReportsConfig();
      if (!token) {
        return reply.code(503).send({ error: 'report ingest disabled — set REPORTS_INGEST_TOKEN' });
      }
      if (!tokenMatches(req.headers.authorization, token)) {
        return reply.code(401).send({ error: 'unauthorized' });
      }

      const q = req.query;
      if (!q.node) return reply.code(400).send({ error: 'missing node query param' });
      if (!(await loadServer(q.node))) {
        return reply.code(400).send({ error: `unknown node: ${q.node}` });
      }

      const id = newId();
      let bytes: number;
      try {
        bytes = await extract(id, req.raw);
      } catch (err) {
        // Never leave a half-extracted report behind for the UI to list.
        await rm(`${cfg.dir}/${id}`, { recursive: true, force: true }).catch(() => {});
        const message = err instanceof Error ? err.message : String(err);
        req.log.error({ msg: 'report extraction failed', id, node: q.node, error: message });
        return reply.code(400).send({ error: `could not extract report: ${message}` });
      }

      const pr = Number(q.pr);
      const meta: ReportMeta = {
        id,
        node: q.node,
        repo: q.repo,
        pr: Number.isInteger(pr) && pr > 0 ? pr : undefined,
        branch: q.branch,
        sha: q.sha,
        runUrl: q.run,
        title: q.title,
        status: q.status === 'passed' ? 'passed' : 'failed',
        bytes,
        createdAt: new Date().toISOString(),
      };
      await writeMeta(meta);

      const dropped = await prune(keep).catch(() => [] as string[]);
      if (dropped.length) req.log.info({ msg: 'pruned old reports', dropped });

      const url = viewUrl(id, authConfig.publicUrl);
      // A failed push must not fail the upload — CI would retry and duplicate
      // the report. sendAlert already swallows its own errors.
      if (meta.status === 'failed') await alertFor(meta, url);

      req.log.info({ msg: 'report ingested', id, node: meta.node, bytes });
      return reply.code(201).send({ id, url });
    },
  );

  app.get<{ Querystring: { node?: string } }>('/api/reports', async (req) => {
    return { reports: await list(req.query.node) };
  });

  app.delete<{ Params: { id: string } }>('/api/reports/:id', async (req, reply) => {
    if (!(await remove(req.params.id))) {
      return reply.code(404).send({ error: 'no such report' });
    }
    return { deleted: true };
  });

  // The report is an ordinary static site: a self-contained index.html plus a
  // sibling data/ dir of .webm/.png attachments it references by RELATIVE URL.
  // Serving the tree under a prefix is all it takes — no rewriting, no
  // `playwright show-report`. @fastify/static also handles Range requests,
  // which is what makes seeking inside a failure video work.
  //
  // The prefix is distinct from the JSON routes above so it can't shadow them,
  // and the global auth guard still covers it (fastify-plugin scope) — the
  // report is only reachable by a logged-in browser.
  await app.register(fastifyStatic, {
    root: cfg.dir,
    prefix: '/api/reports/view/',
    wildcard: true,
    index: ['index.html'],
    // Reports are immutable once written, and their ids are unique per upload.
    cacheControl: true,
    maxAge: '1h',
  });
}
