name: bethany
description: Proxmox host + LXCs
defaults:
  user: root
  key:  ~/.ssh/id_ed25519
servers:
  - { id: proxmox,    host: 192.168.1.215 }
  - { id: plex,       host: 192.168.1.36  }
  - { id: linux-isos, host: 192.168.1.225 }
